# Generated by Django 3.1.2 on 2020-10-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hosiptal Name')),
                ('longtitude', models.FloatField(verbose_name='Longtitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('image', models.ImageField(upload_to=None, verbose_name='Image')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('content', models.TextField()),
                ('publisher', models.CharField(blank=True, max_length=50, null=True, verbose_name='Publisher')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Website')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Source')),
                ('label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
            ],
        ),
    ]
