# Generated by Django 3.1.2 on 2020-10-14 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='newsapi.newsmodel'),
            preserve_default=False,
        ),
    ]
