# Generated by Django 3.1.2 on 2020-10-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0002_location_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
