# Generated by Django 3.1.2 on 2020-10-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0003_remove_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
